{
  "bad": false,
  "new_version": "3.16.0+0",
  "new_version_attempts": {
    "3.0.1.0": 1,
    "3.0.2.0": 2,
    "3.10.1.0": 1,
    "3.16.0+0": 2,
    "3.6.2.0": 1,
    "3.6.3.0": 2,
    "3.8.1+0": 9,
    "3.8.1.0": 0
  },
  "new_version_errors": {
    "3.16.0+0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/16531101944\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 231, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 269, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 324, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '3.16.0+0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not find a hash for the source\n\n",
    "3.8.1+0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '3.8.1+0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/haskell/cabal/archive/Cabal-v{{ version }}.tar.gz'\n"
  }
}