{
  "bad": false,
  "new_version": "0.13.0",
  "new_version_attempts": {
    "0.4.0": 1,
    "0.6.0": 1,
    "0.7.0": 1,
    "0.8.0": 1,
    "0.8.1": 1
  },
  "new_version_errors": {
    "0.4.0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '0.4.0' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '0.4.0': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 46, column 3:\n      home: https://github.com/RoseauT ... \n      ^ (line: 46), 'found duplicate key \"summary\" with value \"Highly capable three-phase load flow solver of Roseau Technologies.\" (original value: \"Three-phase load flow solver\")',   in \"<unicode string>\", line 50, column 3:\n      summary: Highly capable three-ph ... \n      ^ (line: 50), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 411, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 492, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 426, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 113, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 122, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1473, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1362, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 144, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 185, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1473, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1363, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 275, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n"
  }
}