{
  "bad": false,
  "new_version": "2025.9.1",
  "new_version_attempt_ts": {
    "2021.12.0": 1758387191.0,
    "2022.10.2": 1758387191.0,
    "2022.4.1": 1758387191.0,
    "2022.9.2": 1758387191.0,
    "2023.5.0": 1758387191.0,
    "2023.6.0": 1758387191.0,
    "2023.6.1": 1758387191.0,
    "2023.7.0": 1758387191.0,
    "2023.8.0": 1758379991.0,
    "2024.1.1": 1758387191.0,
    "2024.2.1": 1758379991.0
  },
  "new_version_attempts": {
    "2.15.0": 1,
    "2.16.0": 1,
    "2.17.0": 1,
    "2.17.1": 1,
    "2.17.2": 1,
    "2.18.0": 1,
    "2.18.1": 1,
    "2.19.0": 1,
    "2.20.0": 1,
    "2.21.0": 1,
    "2.22.0": 1,
    "2.23.0": 1,
    "2.24.0": 1,
    "2.25.0": 1,
    "2.26.0": 1,
    "2.27.0": 1,
    "2.28.0": 1,
    "2.29.0": 1,
    "2.30.0": 1,
    "2020.12.0": 1,
    "2021.1.0": 1,
    "2021.1.1": 1,
    "2021.10.0": 1,
    "2021.12.0": 1,
    "2021.2.0": 1,
    "2021.3.0": 1,
    "2021.3.1": 1,
    "2021.4.0": 1,
    "2021.4.1": 1,
    "2021.7.0": 1,
    "2021.7.1": 1,
    "2021.7.2": 1,
    "2021.8.1": 1,
    "2021.9.0": 1,
    "2022.10.2": 1,
    "2022.4.1": 1,
    "2022.9.2": 1,
    "2023.5.0": 1,
    "2023.6.0": 1,
    "2023.6.1": 1,
    "2023.7.0": 1,
    "2023.8.0": 3,
    "2024.1.1": 1,
    "2024.2.1": 3,
    "2024.3.0": 1,
    "2024.3.1": 1
  },
  "new_version_errors": {
    "2021.12.0": "We found a problem parsing the recipe for version '2021.12.0': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 40, column 3:\n      home: https://github.com/dask/dask/\n      ^ (line: 40), 'found duplicate key \"summary\" with value \"Parallel Python with task scheduling\" (original value: \"Parallel PyData with Task Scheduling\")',   in \"<unicode string>\", line 44, column 3:\n      summary: Parallel Python with ta ... \n      ^ (line: 44), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 508, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 465, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1452, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 154, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 196, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1453, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
    "2022.10.2": "We found a problem parsing the recipe for version '2022.10.2': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 46, column 3:\n      home: https://github.com/dask/dask/\n      ^ (line: 46), 'found duplicate key \"summary\" with value \"Parallel Python with task scheduling\" (original value: \"Parallel PyData with Task Scheduling\")',   in \"<unicode string>\", line 52, column 3:\n      summary: Parallel Python with ta ... \n      ^ (line: 52), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 513, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 494, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1452, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 154, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 196, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1453, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
    "2022.4.1": "We found a problem parsing the recipe for version '2022.4.1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 40, column 3:\n      home: https://github.com/dask/dask/\n      ^ (line: 40), 'found duplicate key \"summary\" with value \"Parallel Python with task scheduling\" (original value: \"Parallel PyData with Task Scheduling\")',   in \"<unicode string>\", line 44, column 3:\n      summary: Parallel Python with ta ... \n      ^ (line: 44), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 509, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 494, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1452, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 154, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 196, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1453, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
    "2022.9.2": "We found a problem parsing the recipe for version '2022.9.2': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 40, column 3:\n      home: https://github.com/dask/dask/\n      ^ (line: 40), 'found duplicate key \"summary\" with value \"Parallel Python with task scheduling\" (original value: \"Parallel PyData with Task Scheduling\")',   in \"<unicode string>\", line 46, column 3:\n      summary: Parallel Python with ta ... \n      ^ (line: 46), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py\", line 509, in migrate\n    cmeta = CondaMetaYAML(fp.read())\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 494, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 434, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 121, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 131, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1452, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 154, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 196, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1569, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1453, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 294, in check_mapping_key\n    raise DuplicateKeyError(*args)\n",
    "2023.5.0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2023.5.0' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '2023.5.0': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 50, column 3:\n      home: https://github.com/dask/dask/\n      ^ (line: 50), 'found duplicate key \"summary\" with value \"Parallel Python with task scheduling\" (original value: \"Parallel PyData with Task Scheduling\")',   in \"<unicode string>\", line 56, column 3:\n      summary: Parallel Python with ta ... \n      ^ (line: 56), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 411, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 492, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 426, in load\n    return constructor.get_single_data()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 113, in get_single_data\n    return self.construct_document(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 122, in construct_document\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1459, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1348, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 144, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 185, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1459, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1349, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 275, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n",
    "2023.6.0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2023.6.0' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '2023.6.0': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 50, column 3:\n      home: https://github.com/dask/dask/\n      ^ (line: 50), 'found duplicate key \"summary\" with value \"Parallel Python with task scheduling\" (original value: \"Parallel PyData with Task Scheduling\")',   in \"<unicode string>\", line 56, column 3:\n      summary: Parallel Python with ta ... \n      ^ (line: 56), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 411, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 492, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 426, in load\n    return constructor.get_single_data()\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 113, in get_single_data\n    return self.construct_document(node)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 122, in construct_document\n    for _dummy in generator:\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1473, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1362, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 144, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 185, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1473, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1363, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 275, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n",
    "2023.6.1": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2023.6.1' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '2023.6.1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 50, column 3:\n      home: https://github.com/dask/dask/\n      ^ (line: 50), 'found duplicate key \"summary\" with value \"Parallel Python with task scheduling\" (original value: \"Parallel PyData with Task Scheduling\")',   in \"<unicode string>\", line 56, column 3:\n      summary: Parallel Python with ta ... \n      ^ (line: 56), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 411, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 492, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/main.py\", line 426, in load\n    return constructor.get_single_data()\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 113, in get_single_data\n    return self.construct_document(node)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 122, in construct_document\n    for _dummy in generator:\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1473, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1362, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 144, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 185, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1473, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 1363, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.9/site-packages/ruamel/yaml/constructor.py\", line 275, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n",
    "2023.7.0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2023.7.0' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '2023.7.0': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 50, column 3:\n      home: https://github.com/dask/dask/\n      ^ (line: 50), 'found duplicate key \"summary\" with value \"Parallel Python with task scheduling\" (original value: \"Parallel PyData with Task Scheduling\")',   in \"<unicode string>\", line 56, column 3:\n      summary: Parallel Python with ta ... \n      ^ (line: 56), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 411, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 492, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/main.py\", line 426, in load\n    return constructor.get_single_data()\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 113, in get_single_data\n    return self.construct_document(node)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 122, in construct_document\n    for _dummy in generator:\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1473, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1362, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 144, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 185, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1473, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1363, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 275, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n",
    "2023.8.0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2023.8.0' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '2023.8.0': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 50, column 3:\n      home: https://github.com/dask/dask/\n      ^ (line: 50), 'found duplicate key \"summary\" with value \"Parallel Python with task scheduling\" (original value: \"Parallel PyData with Task Scheduling\")',   in \"<unicode string>\", line 56, column 3:\n      summary: Parallel Python with ta ... \n      ^ (line: 56), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 411, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 492, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/main.py\", line 426, in load\n    return constructor.get_single_data()\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 113, in get_single_data\n    return self.construct_document(node)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 122, in construct_document\n    for _dummy in generator:\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1473, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1362, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 144, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 185, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1473, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1363, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 275, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n",
    "2024.1.1": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2024.1.1' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '2024.1.1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 50, column 3:\n      home: https://github.com/dask/dask/\n      ^ (line: 50), 'found duplicate key \"summary\" with value \"Parallel Python with task scheduling\" (original value: \"Parallel PyData with Task Scheduling\")',   in \"<unicode string>\", line 56, column 3:\n      summary: Parallel Python with ta ... \n      ^ (line: 56), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 411, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 514, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/main.py\", line 451, in load\n    return constructor.get_single_data()\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 114, in get_single_data\n    return self.construct_document(node)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 123, in construct_document\n    for _dummy in generator:\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1359, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 145, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 186, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1470, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1360, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 276, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n",
    "2024.2.1": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2024.2.1' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '2024.2.1': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 50, column 3:\n      home: https://github.com/dask/dask/\n      ^ (line: 50), 'found duplicate key \"summary\" with value \"Parallel Python with task scheduling\" (original value: \"Parallel PyData with Task Scheduling\")',   in \"<unicode string>\", line 56, column 3:\n      summary: Parallel Python with ta ... \n      ^ (line: 56), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/update_recipe/version.py\", line 409, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/recipe_parser/_parser.py\", line 514, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/main.py\", line 451, in load\n    return constructor.get_single_data()\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 116, in get_single_data\n    return self.construct_document(node)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 125, in construct_document\n    for _dummy in generator:\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1476, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1365, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 147, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 188, in construct_non_recursive_object\n    for _dummy in generator:\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1476, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 1366, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/ruamel/yaml/constructor.py\", line 278, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n"
  }
}